## Index and Slicing

#### Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).

In [2]:
import numpy as np


arr_2d = np.random.randint(0, 10, size=(5, 5))
print("Original 2D Array:")
print(arr_2d)

sub_array = arr_2d[1:4, 1:4]
print("\n3x3 Sub-array starting from (1, 1):")
print(sub_array)


Original 2D Array:
[[5 8 0 5 9]
 [4 4 1 1 9]
 [6 6 7 3 5]
 [8 5 7 8 7]
 [6 9 4 7 1]]

3x3 Sub-array starting from (1, 1):
[[4 1 1]
 [6 7 3]
 [5 7 8]]


#### From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [3]:

arr_3d = np.random.randint(0, 10, size=(4, 3, 2))
print("\nOriginal 3D Array:")
print(arr_3d)

extracted = arr_3d[:2, :, 1]
print("\nExtracted elements:")
print(extracted)



Original 3D Array:
[[[2 0]
  [5 1]
  [8 3]]

 [[6 4]
  [0 4]
  [4 8]]

 [[2 6]
  [7 2]
  [0 1]]

 [[4 0]
  [5 9]
  [0 9]]]

Extracted elements:
[[0 1 3]
 [4 4 8]]


#### Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

In [5]:

arr_int = np.array([10, 20, 30, 40, 50, 60, 70, 80])

extracted_elements = arr_int[[1, 3, 4, 7]]
print("\nExtracted elements:")
print(extracted_elements)



Extracted elements:
[20 40 50 80]


#### Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].

In [7]:

arr_2d = np.random.randint(0, 20, size=(5, 5))
print("\nOriginal 2D Array:")
print(arr_2d)

selected = arr_2d[[0, 2, 3]][:, [1, 3]]
print("\nSelected rows and columns:")
print(selected)



Original 2D Array:
[[13  7  6 11  8]
 [10  2 17 12 15]
 [19 17  5 19 14]
 [13 19 12 16 19]
 [ 5  5  2 18  8]]

Selected rows and columns:
[[ 7 11]
 [17 19]
 [19 16]]


#### From a 1D array of random integers, extract all elements that are greater than 10.

In [8]:

arr_1d = np.random.randint(0, 20, size=10)
print("\nOriginal 1D Array:")
print(arr_1d)

extracted_greater_than_10 = arr_1d[arr_1d > 10]
print("\nElements greater than 10:")
print(extracted_greater_than_10)



Original 1D Array:
[14 17 12 18 13  6  3  6 10 13]

Elements greater than 10:
[14 17 12 18 13 13]


#### Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.

In [9]:

arr_2d = np.random.randint(0, 20, size=(5, 5))
print("\nOriginal 2D Array:")
print(arr_2d)

arr_2d[arr_2d > 15] = 0
print("\nModified Array with elements > 15 replaced with 0:")
print(arr_2d)



Original 2D Array:
[[ 8  3 17  0  7]
 [18 13 14  9 17]
 [ 5 13 18 11  5]
 [14 15  3 11  5]
 [ 9  2  8  5 10]]

Modified Array with elements > 15 replaced with 0:
[[ 8  3  0  0  7]
 [ 0 13 14  9  0]
 [ 5 13  0 11  5]
 [14 15  3 11  5]
 [ 9  2  8  5 10]]


## Broadcasting

#### Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).




In [13]:
import numpy as np
arr_2d = np.random.randint(0, 10, size=(4, 3))
print("Original 2D Array:")
print(arr_2d)
arr_1d = np.array([1, 2, 3])
print("\n1D Array to add to each row:")
print(arr_1d)
result = arr_2d + arr_1d
print("\nResulting array after addition:")
print(result)


Original 2D Array:
[[2 1 5]
 [7 7 9]
 [1 2 7]
 [8 0 0]]

1D Array to add to each row:
[1 2 3]

Resulting array after addition:
[[ 3  3  8]
 [ 8  9 12]
 [ 2  4 10]
 [ 9  2  3]]


#### Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).


In [14]:

arr_2d = np.random.randint(1, 10, size=(3, 3))
print("\nOriginal 2D Array:")
print(arr_2d)
arr_1d = np.array([2, 3, 4])
print("\n1D Array for multiplication:")
print(arr_1d)
result = arr_2d * arr_1d[:, np.newaxis]  # Ensure broadcasting correctly
print("\nResulting array after multiplication:")
print(result)



Original 2D Array:
[[2 6 5]
 [6 4 3]
 [1 7 1]]

1D Array for multiplication:
[2 3 4]

Resulting array after multiplication:
[[ 4 12 10]
 [18 12  9]
 [ 4 28  4]]


#### Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [15]:

arr1 = np.random.randint(1, 10, size=(3, 1))
arr2 = np.random.randint(1, 10, size=(1, 4))

print("\nFirst 2D Array (shape 3, 1):")
print(arr1)
print("\nSecond 2D Array (shape 1, 4):")
print(arr2)
result = arr1 + arr2
print("\nResulting array after element-wise addition:")
print(result)



First 2D Array (shape 3, 1):
[[6]
 [9]
 [4]]

Second 2D Array (shape 1, 4):
[[9 9 5 4]]

Resulting array after element-wise addition:
[[15 15 11 10]
 [18 18 14 13]
 [13 13  9  8]]



#### Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [16]:

arr_3d = np.random.randint(1, 10, size=(2, 3, 4))
print("\nOriginal 3D Array:")
print(arr_3d)

arr_add = np.random.randint(1, 5, size=(3, 4))
print("\n2D Array to add to each 2D slice:")
print(arr_add)

result = arr_3d + arr_add[np.newaxis, :, :]
print("\nResulting array after addition:")
print(result)



Original 3D Array:
[[[8 6 4 5]
  [3 3 3 8]
  [1 7 7 4]]

 [[2 8 6 1]
  [6 6 6 4]
  [2 6 6 2]]]

2D Array to add to each 2D slice:
[[1 2 1 2]
 [4 2 3 4]
 [3 3 1 4]]

Resulting array after addition:
[[[ 9  8  5  7]
  [ 7  5  6 12]
  [ 4 10  8  8]]

 [[ 3 10  7  3]
  [10  8  9  8]
  [ 5  9  7  6]]]


## Some more

#### Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.






In [24]:
import numpy as np
arr_2d = np.random.randint(0, 10, size=(6, 6))
print("Original 2D Array:")
print(arr_2d)

extracted = arr_2d[::2, ::2]
print("\nExtracted every second row and column:")
print(extracted)

arr_add = np.array([1, 2, 3])  # Note: Adjusting to match the shape of extracted rows
print("\n1D Array to add to each row:")
print(arr_add)

result = extracted + arr_add[:, np.newaxis]  # Adjusting broadcasting dimensions
print("\nResult after adding 1D array to each row:")
print(result)


Original 2D Array:
[[9 4 5 7 8 9]
 [5 9 3 8 4 3]
 [3 8 1 4 1 2]
 [5 8 2 2 8 9]
 [5 4 8 1 7 7]
 [4 6 4 0 8 0]]

Extracted every second row and column:
[[9 5 8]
 [3 1 1]
 [5 8 7]]

1D Array to add to each row:
[1 2 3]

Result after adding 1D array to each row:
[[10  6  9]
 [ 5  3  3]
 [ 8 11 10]]


#### From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [27]:

arr_3d = np.random.randint(0, 10, size=(4, 3, 2))

sub_array = arr_3d[:, 1:, :]  # Shape will be (4, 2, 2)
arr_subtract = np.random.randint(0, 5, size=(2, 2)) 
print("\n2D Array for subtraction:")
print(arr_subtract)
result = sub_array - arr_subtract[np.newaxis, :, :]
print("\nResult after subtraction using broadcasting:")
print(result)



2D Array for subtraction:
[[2 0]
 [2 1]]

Result after subtraction using broadcasting:
[[[ 4  8]
  [-2  7]]

 [[ 2  6]
  [ 7  7]]

 [[ 3  7]
  [-2  4]]

 [[ 1  2]
  [ 4  4]]]


#### Given a 2D array, extract the diagonal elements and create a 1D array.

In [29]:

arr_2d = np.random.randint(0, 10, size=(4, 4))
print("\nOriginal 2D Array:")
print(arr_2d)

diagonal_elements = np.diag(arr_2d)
print("\nDiagonal elements as 1D array:")
print(diagonal_elements)



Original 2D Array:
[[5 0 0 4]
 [9 9 6 8]
 [5 5 2 2]
 [4 2 8 6]]

Diagonal elements as 1D array:
[5 9 2 6]


#### Use slicing to reverse the order of elements in each row of a 2D array.

In [31]:

arr_2d = np.random.randint(0, 10, size=(5, 5))
print("\nOriginal 2D Array:")
print(arr_2d)
reversed_array = arr_2d[:, ::-1]
print("\nReversed order of elements in each row:")
print(reversed_array)



Original 2D Array:
[[0 3 4 3 2]
 [3 3 0 5 0]
 [5 6 1 2 6]
 [8 2 4 3 3]
 [5 0 3 0 0]]

Reversed order of elements in each row:
[[2 3 4 3 0]
 [0 5 0 3 3]
 [6 2 1 6 5]
 [3 3 4 2 8]
 [0 0 3 0 5]]


#### Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [37]:
arr_3d = np.random.randint(0, 10, size=(4, 5, 6))
print("\nOriginal 3D Array:")
print(arr_3d)

sub_array = arr_3d[:2, :3, :4]
add_array = np.array([1, 2, 3, 4])
sub_array + add_array


Original 3D Array:
[[[9 1 1 7 0 4]
  [4 6 5 2 4 5]
  [7 0 8 9 7 8]
  [2 3 2 4 3 7]
  [5 5 2 8 9 8]]

 [[3 0 3 0 8 0]
  [4 4 5 6 5 3]
  [1 1 9 9 0 3]
  [8 2 6 9 4 9]
  [1 7 7 8 3 0]]

 [[9 3 3 2 6 6]
  [9 0 0 5 8 0]
  [4 7 5 0 4 9]
  [9 8 2 9 1 1]
  [0 7 2 1 6 3]]

 [[9 3 2 7 1 9]
  [6 4 2 4 2 5]
  [8 5 6 9 3 0]
  [0 3 3 3 4 7]
  [0 5 4 2 3 8]]]


array([[[10,  3,  4, 11],
        [ 5,  8,  8,  6],
        [ 8,  2, 11, 13]],

       [[ 4,  2,  6,  4],
        [ 5,  6,  8, 10],
        [ 2,  3, 12, 13]]])

#### Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.


In [36]:

arr_2d = np.random.randint(0, 10, size=(5, 3))
print("\nOriginal 2D Array:")
print(arr_2d)

arr_2d[:, 2] = arr_2d[:, 0] + arr_2d[:, 1]
print("\nResult after setting last column:")
print(arr_2d)



Original 2D Array:
[[2 3 2]
 [3 3 8]
 [9 9 9]
 [0 5 3]
 [6 0 4]]

Result after setting last column:
[[ 2  3  5]
 [ 3  3  6]
 [ 9  9 18]
 [ 0  5  5]
 [ 6  0  6]]


#### Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.





In [47]:
import numpy as np

# Create a 2D array
arr_2d = np.random.randint(0, 10, size=(6, 6))
print("Original 2D Array:")
print(arr_2d)

# Extract every second row and column
extracted = arr_2d[1::2, 1::2]

# Create a 1D array to add to each row of the sliced array
arr_add = np.array([1, 2, 3])  # Adjusted to match the number of rows in extracted
result = extracted + arr_add[:, np.newaxis]
print("\nResult after adding 1D array to each row:")
print(result)


Original 2D Array:
[[0 2 4 9 5 8]
 [6 6 1 6 9 0]
 [1 5 3 1 3 1]
 [4 8 1 5 7 9]
 [5 8 1 2 5 5]
 [5 9 6 9 2 4]]

Result after adding 1D array to each row:
[[ 7  7  1]
 [10  7 11]
 [12 12  7]]


#### From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [49]:
# Create a 3D array
arr_3d = np.random.randint(0, 10, size=(3, 2, 1))
print("\nOriginal 3D Array:")
print(arr_3d)


sub_array = arr_3d[:, :, 0]  # Shape will be (3, 2)

arr_subtract = np.random.randint(0, 5, size=(3, 2))  # Adjusted to match the shape of sub_array slices
result = sub_array - arr_subtract
print("\nResult after subtraction using broadcasting:")
print(result)



Original 3D Array:
[[[2]
  [8]]

 [[6]
  [5]]

 [[0]
  [4]]]

Result after subtraction using broadcasting:
[[-2  7]
 [ 3  4]
 [-3  4]]


#### Given a 2D array, extract the diagonal elements and create a 1D array.

In [50]:
# Create a 2D array
arr_2d = np.random.randint(0, 10, size=(4, 4))
print("\nOriginal 2D Array:")
print(arr_2d)

# Extract diagonal elements
diagonal_elements = np.diag(arr_2d)
print("\nDiagonal elements as 1D array:")
print(diagonal_elements)



Original 2D Array:
[[6 1 4 5]
 [0 6 5 8]
 [9 2 0 0]
 [7 2 1 5]]

Diagonal elements as 1D array:
[6 6 0 5]



#### Use slicing to reverse the order of elements in each row of a 2D array.

In [51]:
# Create a 2D array
arr_2d = np.random.randint(0, 10, size=(5, 5))
print("\nOriginal 2D Array:")
print(arr_2d)

# Reverse the order of elements in each row using slicing
reversed_array = arr_2d[:, ::-1]
print("\nReversed order of elements in each row:")
print(reversed_array)



Original 2D Array:
[[1 1 0 7 2]
 [3 4 2 2 5]
 [0 2 9 5 1]
 [7 1 1 8 0]
 [8 3 1 7 2]]

Reversed order of elements in each row:
[[2 7 0 1 1]
 [5 2 2 4 3]
 [1 5 9 2 0]
 [0 8 1 1 7]
 [2 7 1 3 8]]


#### Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [54]:

arr_3d = np.random.randint(0, 10, size=(3, 2, 1))
print("Original 3D Array:")
print(arr_3d)

sub_array = arr_3d[:, :, 0]  # Shape will be (3, 2)
arr_add = np.array([1, 2, 3, 4])  # Adjusted to match the shape along the third axis
result = sub_array + arr_add[:, np.newaxis, np.newaxis]
print("\nResult after addition using broadcasting:")
print(result)

Original 3D Array:
[[[1]
  [3]]

 [[5]
  [2]]

 [[4]
  [8]]]

Result after addition using broadcasting:
[[[ 2  4]
  [ 6  3]
  [ 5  9]]

 [[ 3  5]
  [ 7  4]
  [ 6 10]]

 [[ 4  6]
  [ 8  5]
  [ 7 11]]

 [[ 5  7]
  [ 9  6]
  [ 8 12]]]
