# Problems

#### Task 1: Create a 1D NumPy array containing the integers from 0 to 9.

In [1]:
import numpy as np

In [2]:
array_1d = np.arange(10)
print("1D Array:", array_1d)


1D Array: [0 1 2 3 4 5 6 7 8 9]


#### Task 2: Create a 2D NumPy array (3x3) containing random integers between 1 and 20

In [5]:
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array (3x3):\n", array_2d)

2D Array (3x3):
 [[ 3  2  5]
 [14  3 11]
 [14 11  1]]



#### Task 3: Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones

In [6]:
array_3d = np.ones((2, 3, 4))
print("3D Array (2x3x4):\n", array_3d)


3D Array (2x3x4):
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


#### Task 4: Add two 1D arrays element-wise

In [8]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_arrays = np.add(array1, array2)
print("Element-wise addition of 1D arrays:", sum_arrays)

Element-wise addition of 1D arrays: [5 7 9]


#### Task 5: Multiply two 2D arrays element-wise

In [9]:
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])
product_arrays = np.multiply(array3, array4)
print("Element-wise multiplication of 2D arrays:\n", product_arrays)

Element-wise multiplication of 2D arrays:
 [[ 5 12]
 [21 32]]


#### Task 6: Calculate the dot product of two matrices

In [10]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
print("Dot product of matrices:\n", dot_product)


Dot product of matrices:
 [[19 22]
 [43 50]]


#### Task 7: Calculate the mean, median, and standard deviation of a 1D array


In [11]:
array_1d_stats = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(array_1d_stats)
median = np.median(array_1d_stats)
std_dev = np.std(array_1d_stats)
print("Mean:", mean, "Median:", median, "Standard Deviation:", std_dev)

Mean: 5.5 Median: 5.5 Standard Deviation: 2.8722813232690143


#### Task 8: Find the maximum and minimum values in a 2D array

In [12]:
array_2d_stats = np.random.randint(1, 101, size=(5, 5))
max_value = np.max(array_2d_stats)
min_value = np.min(array_2d_stats)
print("2D Array:\n", array_2d_stats)
print("Maximum value:", max_value, "Minimum value:", min_value)


2D Array:
 [[ 20  32  97  34  73]
 [ 17  39  10   9  49]
 [ 48  49  44  84  76]
 [ 33   3  78   3  37]
 [ 76 100  62  90  53]]
Maximum value: 100 Minimum value: 3


#### Task 9: Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1

In [13]:
normal_dist_array = np.random.normal(0, 1, 1000)
print("Array of 1000 random numbers from normal distribution:\n", normal_dist_array)

Array of 1000 random numbers from normal distribution:
 [-1.17885907e+00 -1.04704179e+00 -1.04102275e+00 -2.77941999e-01
  3.03762060e+00  1.09687251e+00 -1.22960094e+00  5.92293591e-01
  1.70339392e+00  8.21571036e-01 -6.49209971e-01  7.68562235e-01
 -1.55710477e+00 -4.34592699e-01  4.02572355e-01 -1.37865721e+00
  1.38986335e-01  8.34414267e-01 -2.51777409e-01 -1.23220540e+00
 -3.33113064e-01  5.56500455e-01 -1.62622671e+00 -6.79265792e-02
 -1.08395144e+00 -6.60979278e-01  8.58788596e-01  1.13860347e+00
  3.59929076e-01  1.01441464e+00  1.75973538e-01 -5.60032374e-01
 -2.06945686e+00  1.84441921e+00 -8.99817026e-01 -1.30200048e+00
  4.93493477e-01 -5.42763952e-01 -6.47960063e-01  1.07212303e+00
  5.47584148e-01 -1.19088120e-01  3.03514985e-01 -1.00298421e+00
 -1.04772910e+00 -1.71891507e+00  1.33664000e+00  7.56133707e-01
  1.21648033e-01  8.94621711e-01 -3.22882790e-01 -1.56252945e+00
  1.34289032e+00  1.26605776e-01 -7.29563762e-01 -3.87030613e-01
  3.30353633e-01 -2.56218840e-02  

#### Task 10: Create a 2D array of shape (5, 5) with random integers from a uniform distribution between 10 and 50

In [14]:
uniform_dist_array = np.random.randint(10, 51, size=(5, 5))
print("2D Array with random integers from uniform distribution (10 to 50):\n", uniform_dist_array)

2D Array with random integers from uniform distribution (10 to 50):
 [[19 50 11 24 31]
 [50 15 35 15 20]
 [17 27 36 45 41]
 [26 10 46 18 21]
 [23 10 10 32 24]]


#### Task 11: Calculate the cumulative sum of a 1D array

In [15]:
cumulative_sum = np.cumsum(array_1d_stats)
print("Cumulative sum of 1D array:", cumulative_sum)

Cumulative sum of 1D array: [ 1  3  6 10 15 21 28 36 45 55]


#### Task 12: Compute the correlation coefficient matrix of a 2D array


In [16]:
correlation_matrix = np.corrcoef(array_2d_stats)
print("Correlation coefficient matrix:\n", correlation_matrix)

Correlation coefficient matrix:
 [[ 1.          0.03915513 -0.08849013  0.80823901 -0.73458799]
 [ 0.03915513  1.          0.13651226 -0.23248492 -0.16368475]
 [-0.08849013  0.13651226  1.         -0.45935748 -0.0507386 ]
 [ 0.80823901 -0.23248492 -0.45935748  1.         -0.77809864]
 [-0.73458799 -0.16368475 -0.0507386  -0.77809864  1.        ]]


#### Task 13: Simulate rolling a six-sided die 1000 times and count the frequency of each outcome

In [17]:
die_rolls = np.random.randint(1, 7, size=1000)
outcome_counts = np.bincount(die_rolls)[1:7]  # We use [1:7] to exclude the zero-count for value 0 which is not a die roll outcome
print("Frequency of each outcome from rolling a six-sided die 1000 times:", outcome_counts)

Frequency of each outcome from rolling a six-sided die 1000 times: [161 170 157 156 178 178]


#### Problems from the task 9

#### Q1: Calculate the mean, median, and mode for the following data set: 4, 8, 6, 5, 3, 8, 7.

In [22]:
import numpy as np

data = np.array([4, 8, 6, 5, 3, 8, 7])

mean = np.mean(data)
median = np.median(data)
(mode, count) = np.unique(data, return_counts=True)
mode = mode[np.argmax(count)]

mean, median, mode


(5.857142857142857, 6.0, 8)

#### Q2: In a normal distribution, 68% of the data falls within one standard deviation of the mean. If a dataset has a mean of 50 and a standard deviation of 5, between what two values does 68% of the data lie?

In [25]:
mean = 50
std_dev = 5

lower_bound = mean - std_dev
upper_bound = mean + std_dev

print("lower bound:",lower_bound)
print("upper bound:",upper_bound)


lower bound: 45
upper bound: 55


#### Q3: A fair coin is flipped 10 times. What is the probability of getting exactly 6 heads?

In [26]:
import numpy as np
from math import comb

n = 10
p = 0.5
k = 6

probability = comb(n, k) * (p ** k) * ((1 - p) ** (n - k))

probability


0.205078125