# Linear algebra and calculus in NumPy

In [130]:
import numpy as np
import scipy.linalg

## Linear Algebra Tasks

### Task 1: Matrix Creation and Manipulation

 **Zero Matrix:** A matrix where all elements are zeros.

In [49]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Identity Matrix:** A square matrix with ones on the diagonal and zeros elsewhere.

In [60]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Random Matrix:** A matrix with random values.

In [63]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.73538476 0.2232925  0.18168651]
 [0.56464133 0.3378251  0.88656115]
 [0.05309553 0.68287129 0.78090427]]


**Performing Basic Matrix Operations**

In [71]:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
addition = A + B
print("Matrix Addition:\n", addition)

# Subtraction
subtraction = A - B
print("Matrix Subtraction:\n", subtraction)

# Multiplication (element-wise)
element_wise_mult = A * B
print("Element-wise Multiplication:\n", element_wise_mult)

# Matrix Multiplication
matrix_mult = np.dot(A, B)
print("Matrix Multiplication:\n", matrix_mult)

# Transpose of a matrix
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

# Determinant of a matrix
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Inverse of a matrix
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)


Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [69]:
# Matrix Multiplication
matrix_mult = np.dot(A, B)
print("Matrix Multiplication:\n", matrix_mult)

# Transpose of a matrix
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

# Determinant of a matrix
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Inverse of a matrix
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Task 2: Solving Linear Equations

**Solve a System of Linear Equations**

In [82]:
# 2x + y = 5
# 3x - 2y = -8
# Coefficient matrix
A = np.array([[2, 1], [3, -2]])
# Constant vector
b = np.array([5, -8])
x = np.linalg.solve(A, b)
print(x)

[0.28571429 4.42857143]


**Implement Matrix Factorization Methods**

In [128]:
# LU decomposition

P, L, U = scipy.linalg.lu(A)
print("P",P)
print("L",L)
print("U",U)

P [[0. 1.]
 [1. 0.]]
L [[1.         0.        ]
 [0.66666667 1.        ]]
U [[ 3.         -2.        ]
 [ 0.          2.33333333]]


In [95]:
# QR decomposition
Q, R = np.linalg.qr(A)
print("Q", Q)
print("R", R)

Q [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]
R [[-3.60555128  1.10940039]
 [ 0.         -1.94145069]]


## Task 3: Eigenvalues and Eigenvectors

**Calculate Eigenvalues and Eigenvectors**

In [110]:

C = np.array([[1, 2], [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [ 3. -1.]
Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [107]:
# Verify by reconstructing the original matrix
reconstructed_matrix = np.dot(np.dot(eigenvectors, np.diag(eigenvalues)), np.linalg.inv(eigenvectors))
print(reconstructed_matrix)

[[1. 2.]
 [2. 1.]]


## Task 4: Vector Operations

**Perform Basic Vector Operations**

In [126]:

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
vector_addition = v1 + v2
print("Vector Addition:", vector_addition)

# Dot product
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

# Cross product
cross_product = np.cross(v1, v2)
print("Cross Product:", cross_product)

# Normalize a vector
norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print("Normalized v1:", normalized_v1)

# Compute vector norms
norm_v2 = np.linalg.norm(v2)
print("Norm of v2:", norm_v2)



Vector Addition: [5 7 9]
Dot Product: 32
Cross Product: [-3  6 -3]
Normalized v1: [0.26726124 0.53452248 0.80178373]
Norm of v2: 8.774964387392123


## Task 5: Matrix Decomposition

**Implementing Principal Component Analysis (PCA) using SVD**

In [121]:
X = np.array([[1, 2], [3, 4], [5, 6]])

# Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(X)
principal_components = VT.T
print(principal_components)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Calculus Tasks

### Task 1: Numerical Differentiation

**Compute Numerical Derivative of a Function**

In [134]:
def f(x):
    return x**2 + np.sin(x)
def forward_difference(f, x, h):
    return (f(x + h) - f(x)) / h
def backward_difference(f, x, h):
    return (f(x) - f(x - h)) / h
def central_difference(f, x, h):
    return (f(x + h/2) - f(x - h/2)) / h

**Now testing the methods**

In [141]:
x0 = 1.0
h = 0.001

derivative_forward = forward_difference(f, x0, h)
derivative_backward = backward_difference(f, x0, h)
derivative_central = central_difference(f, x0, h)

print("Forward Difference:", derivative_forward)
print("Backward Difference:", derivative_backward)
print("Central Difference:", derivative_central)

Forward Difference: 2.5408814803600244
Backward Difference: 2.5397229512751363
Central Difference: 2.5403022833554445


### Task 2: Numerical Integration

**Compute Numerical Integral of a Function**

In [146]:
def g(x):
    return np.sin(x)
def trapezoidal_rule(f, a, b, n):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    return h * (np.sum(y) - 0.5 * (y[0] + y[-1]))
def simpsons_rule(f, a, b, n):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    return h/3 * (y[0] + y[-1] + 4 * np.sum(y[1:-1:2]) + 2 * np.sum(y[2:-2:2]))

**Now testing the functions**

In [153]:
a = 0.5
b = np.pi
n = 1000

integral_trapezoidal = trapezoidal_rule(g, a, b, n)
integral_simpsons = simpsons_rule(g, a, b, n)

print("Trapezoidal Rule:", integral_trapezoidal)
print("Simpson's Rule:", integral_simpsons)

Trapezoidal Rule: 1.877581470074148
Simpson's Rule: 1.8775825618908804


### Task 3: Partial Derivatives

**Calculate Partial Derivatives of Multivariable Functions**

In [168]:
def h(x, y):
    return x**2 + np.cos(y)
def partial_derivative_x(f, x, y, h):
    return (f(x + h, y) - f(x, y)) / h
def partial_derivative_y(f, x, y, h):
    return (f(x, y + h) - f(x, y)) / h

**Now testing the functions**

In [170]:
x0 = 1.0
y0 = 0.5
h_value = 0.001
partial_x = partial_derivative_x(h, x0, y0, h_value)
partial_y = partial_derivative_y(h, x0, y0, h_value)
print("Partial derivative with respect to x:", partial_x)
print("Partial derivative with respect to y:", partial_y)

Partial derivative with respect to x: 2.0009999999996975
Partial derivative with respect to y: -0.479864249944395


### Task 4: Optimization

**Solving Optimization Problems with Constraints**

In [179]:
from scipy.optimize import minimize
def objective(x):
    return x[0]**2 + x[1]**2
def constraint1(x):
    return x[0] + x[1] - 1


In [181]:
x0 = np.array([0.5, 0.5])
# Defining bounds and constraints
bounds = ((0, None), (0, None))
constraints = {'type': 'eq', 'fun': constraint1}
# Solving the optimization problem
result = minimize(objective, x0, bounds=bounds, constraints=constraints)
print("Optimal solution:", result.x)
print("Optimal objective value:", result.fun)

Optimal solution: [0.5 0.5]
Optimal objective value: 0.5
